---
# tasks file for test-role
- name: Run remote code
  remote_test:
  register: my_remote_variable

- name: Show remote data
  debug:
    msg: "Remote data {{ my_remote_variable.ansible_facts }}"      

- name: Now run the plugin
  process_remote_data:
    remote_data: "{{ my_remote_variable }}"
  register: my_action_variable

- name: Print the action result if changed
  ansible.builtin.debug:
    msg: "Changed: {{ my_action_variable.remote_host }}"
  when: my_action_variable.changed

- name: Print the action result if not changed
  ansible.builtin.debug:
    msg: "Not changed: {{ my_action_variable.remote_host }}"
  when: not my_action_variable.changed